In [20]:
#1
import numpy as np

In [21]:
#2
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
#3
np.full((3,3), True)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [23]:
#4
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
np.where(arr % 2 > 0)

(array([1, 3, 5, 7, 9]),)

In [24]:
#5
arr[arr % 2 > 0] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [25]:
#6
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
np.where(arr %2 > 0, -1, arr)

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [26]:
#7
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [27]:
#8
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [28]:
#9
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.hstack((a,b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [29]:
#10
a = np.array([1,2,3])
np.r_[[a[0]]*3, [a[1]]*3,[a[2]]*3, a,a,a]
np.r_[a.repeat(3), np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [30]:
#11
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [31]:
#12
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
res = np.where(a == np.intersect1d(a, b))
print(res)
np.delete(a, res)

(array([4]),)


array([1, 2, 3, 4])

In [32]:
#13
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b)

(array([1, 3, 5, 7]),)

In [33]:
#14
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[np.where(np.logical_and(a>=5, a <=10))]
#optimal
a[(a>=5) & (a <=10)]

array([ 6,  9, 10])

In [34]:
#15
def pair_max(x, y):
    """Get the maximum of two items"""
    return np.where(a >= b, a, b)

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a, b)
#second solution
#we will convert maxx function to working with vectors
#usin np.vectorize
def maxx(x,y):
    if x>= y:
        return x
    else:
        return y
pair_maxx = np.vectorize(maxx)
pair_maxx(a, b)

array([6, 7, 9, 8, 9, 7, 5])

In [37]:
#16
arr = np.arange(9).reshape(3,3)
print(arr)
arr[:,[0, 1]] = arr[:,[1, 0]]
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [51]:
#17
arr = np.arange(9).reshape(3,3)
print(arr)
arr[[0,1,2],:] = arr[[1,0,2],:]
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]
 [0 1 2]
 [6 7 8]]


In [58]:
#18
#.1
arr = np.arange(9).reshape(3,3)
arr[[0,1,2],:] = arr[[2,1,0],:]
print(arr)
#.2
arr[::-1]

[[6 7 8]
 [3 4 5]
 [0 1 2]]


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [71]:
#19
#.1
arr = np.arange(9).reshape(3,3)
np.flip(arr, 1)
#arr
#.2
arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [74]:
#20
sampl = np.random.uniform(low=5, high=10, size=(15,))
sampl.reshape(5,3)

array([[7.62924689, 9.74483318, 5.83146661],
       [9.63662432, 5.01957967, 6.46166304],
       [6.1591668 , 9.93629937, 5.36803659],
       [5.9669167 , 8.90655221, 7.14909456],
       [8.02069211, 6.33004771, 5.42117706]])